name: 'Check Employee'
description: 'Check if user is a GitHub Employee'
inputs:
  token:  
    description: 'The token used to interact with GitHub'
    required: true
outputs:
  employee: 
    description: 'Boolean of whether the user is a GitHub employee'
runs:
  using: 'node16'
  main: 'index.js'